### ISSUE TITLE
Provide environment setup

### ISSUE THREAD

**Issue by mabergerx** [gstrezoski/InfoVis-Framework-2020#3]
For the people that miss packages, the virtualenv I use for this project contains the following:

bokeh==1.4.0
Click==7.0
Flask==1.1.1
Flask-SocketIO==4.2.1
itsdangerous==1.1.0
Jinja2==2.11.1
joblib==0.14.1
MarkupSafe==1.1.1
numpy==1.18.1
packaging==20.1
pandas==1.0.0
Pillow==7.0.0
pyparsing==2.4.6
python-dateutil==2.8.1
python-engineio==3.11.2
python-socketio==4.4.0
pytz==2019.3
PyYAML==5.3
scikit-learn==0.22.1
scipy==1.4.1
six==1.14.0
tornado==6.0.3
Werkzeug==0.16.1

But maybe would be cool if the author adds the requirements.txt ;)

**Comment by gstrezoski** [comment]
Thanks @mabergerx 

Requirements file added with the latest commit.
